<?php
/**
 * @package    Fuel
 * @version    2.0
 * @author     Fuel Development Team
 * @license    MIT License
 * @copyright  2010 - 2013 Fuel Development Team
 * @link       http://fuelphp.com
 */

/**
 * index_file - The name of the main bootstrap file.
 *
 * Set this to 'index.php if you don't use URL rewriting
 */
static::$config->indexFile = false;

/**
 * base_url - The base URL of the application.
 * MUST contain a trailing slash (/)
 *
 * You can set this to a full or relative URL:
 *
 *     $env->baseUrl = '/foo/';
 *     $env->baseUrl = 'http://foo.com/';
 *
 * Set this to null to have it automatically detected.
 */
static::$config->baseUrl = null;

/**
 * url_suffix - Any suffix that needs to be added to
 * URL's generated by Fuel. If the suffix is an extension,
 * make sure to include the dot
 *
 *     $env->urlSuffix = '.html';
 *
 * Set this to an empty string if no suffix is used
 */
static::$config->urlSuffix  = '';

/**
 * profiling - Enable or Disable the profiler
 */
static::$config->profiling  = false;

/**
 * Callback to use with ob_start(), set this to 'ob_gzhandler' for gzip encoding of output
 */
static::$config->ob_callback  = null;

/**
 * DateTime settings
 *
 * server_gmt_offset	in seconds the server offset from gmt timestamp when time() is used
 * default_timezone		optional, if you want to change the server's default timezone
 */
static::$config->server_gmt_offset  = 0;
static::$config->default_timezone   = null;
