<?php
/**
 * @package    Fuel
 * @version    2.0
 * @author     Fuel Development Team
 * @license    MIT License
 * @copyright  2010 - 2013 Fuel Development Team
 * @link       http://fuelphp.com
 */

/**
 * NOTICE:
 *
 * This is the global configuration for the FuelPHP framework. It contains
 * configuration which is global for all installed applications.
 */


return array(

	/**
	 * base_url - The base URL of the application.
	 * MUST contain a trailing slash (/)
	 *
	 * You can set this to a full or relative URL:
	 *
	 *     'baseUrl' => '/foo/',
	 *     'baseUrl' => 'http://foo.com/'
	 *
	 * Set this to null to have it automatically detected.
	 */
	'baseUrl'  => null,

	/**
	 * urlSuffix - Any suffix that needs to be added to
	 * URL's generated by Fuel. If the suffix is an extension,
	 * make sure to include the dot
	 *
	 *     'urlSuffix' => '.html',
	 *
	 * Set this to an empty string if no suffix is used
	 */
	'urlSuffix'  => '',

	/**
	 * indexFile - The name of the main bootstrap file.
	 *
	 * Set this to 'index.php if you don't use URL rewriting
	 */
	'indexFile' => false,

	/**
	 * profiling - Whether or not the Profiler is enabled
	 */
	'profiling'  => false,

	/**
	 * Callback to use with ob_start(), set this to 'ob_gzhandler' for gzip encoding of output
	 */
	'ob_callback'  => null,

	/**
	 * DateTime settings
	 *
	 * server_gmt_offset	in seconds the server offset from gmt timestamp when time() is used
	 * default_timezone		optional, if you want to change the server's default timezone
	 */
	'server_gmt_offset'  => 0,
	'default_timezone'   => null,
);
